table 'MOD Flex Table Metrics'
	lineageTag: 9ad5d329-2db1-4474-a2d1-76b8244d3021

	measure 'Flex Table Selected Value' =
			
			VAR SelectedMeasure = SELECTEDVALUE('MOD Flex Table Measure Selector'[MeasureKey])
			VAR AxisKey = SELECTEDVALUE('MOD Flex Table Axis'[DimensionKey])
			VAR AxisValue = SELECTEDVALUE('MOD Flex Table Axis'[AxisLabel])
			VAR BaseMetric =
			    SWITCH(
			        SelectedMeasure,
			        "sales_values", [Flex Input Sales Values],
			        "sales_units", [Flex Input Sales Units],
			        "counting_units", [Flex Input Counting Units],
			        "promo_spend", [Flex Input Promo Spend],
			        "promo_details", [Flex Input Promo Details],
			        "promo_contacts", [Flex Input Promo Contacts],
			        "promo_weighted_calls", [Flex Input Promo Weighted Calls],
			        "fin_act", [Flex Input Fin ACT],
			        "fin_bdg", [Flex Input Fin BDG],
			        "fin_act_py", [Flex Input Fin ACT PY],
			        BLANK()
			    )
			RETURN
			SWITCH(
			    AxisKey,
			    "Molecule",
			        CALCULATE(
			            BaseMetric,
			            KEEPFILTERS(TREATAS({AxisValue}, T_DIM_MOLECULE[MoleculeNorm]))
			        ),
			    "Country",
			        CALCULATE(
			            BaseMetric,
			            KEEPFILTERS(TREATAS({AxisValue}, T_DIM_COUNTRY[Country]))
			        ),
			    "Corporation",
			        CALCULATE(
			            BaseMetric,
			            KEEPFILTERS(TREATAS({AxisValue}, T_DIM_CORPORATION[Corporation]))
			        ),
			    "Product",
			        CALCULATE(
			            BaseMetric,
			            KEEPFILTERS(TREATAS({AxisValue}, T_DIM_PRODUCT[Product]))
			        ),
			    "Quarter",
			        CALCULATE(
			            BaseMetric,
			            KEEPFILTERS(TREATAS({AxisValue}, T_DIM_QUARTER[QuarterKey]))
			        ),
			    "ATC4",
			        CALCULATE(
			            BaseMetric,
			            KEEPFILTERS(TREATAS({AxisValue}, T_DIM_ACT4[ATC4]))
			        ),
			    BLANK()
			)
		formatString: #,0.00
		lineageTag: 3ad9ece3-2136-42e7-b713-8e3df6e2471a

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Flex Table Row Has Data' =
			
			VAR NonBlankMeasureCount =
			    SUMX(
			        VALUES('MOD Flex Table Measure Selector'[MeasureKey]),
			        VAR CurrentMeasureKey = 'MOD Flex Table Measure Selector'[MeasureKey]
			        RETURN
			            IF(
			                NOT ISBLANK(
			                    CALCULATE(
			                        [Flex Table Selected Value],
			                        TREATAS({CurrentMeasureKey}, 'MOD Flex Table Measure Selector'[MeasureKey])
			                    )
			                ),
			                1,
			                0
			            )
			    )
			RETURN
			IF(NonBlankMeasureCount > 0, 1)
		formatString: 0
		lineageTag: 82c527ac-c700-4f50-9f8a-fba2ab2bcc95

	measure 'Flex Table Title' =
			
			VAR SelectedDimensions =
			    CONCATENATEX(
			        VALUES('MOD Flex Table Axis'[DimensionLabel]),
			        'MOD Flex Table Axis'[DimensionLabel],
			        ", ",
			        'MOD Flex Table Axis'[DimensionSort],
			        ASC
			    )
			RETURN
			"Flexible Core Metrics Table | " & COALESCE(SelectedDimensions, "Molecule")
		lineageTag: f7b9e2a3-fc89-4533-ae54-ef56c48fc917

	column Column
		isHidden
		formatString: 0
		lineageTag: 2e00cded-66a0-47a9-a699-ecb837fa9e1b
		summarizeBy: sum
		isNameInferred
		sourceColumn: [Column]

		annotation SummarizationSetBy = Automatic

	partition 'MOD Flex Table Metrics' = calculated
		mode: import
		source = Row("Column", BLANK())
