table 'MOD Finance Compare Metrics'

	measure 'Selected Reference Value' = [Metric Compare (Selected)]

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Primary vs (Selected) abs' =
			
			VAR comp = [Metric Compare (Selected)]
			RETURN IF( ISBLANK(comp), BLANK(), [Input Primary Measure] - comp )

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Primary vs (Selected) %' =
			
			VAR comp = [Metric Compare (Selected)]
			RETURN IF( ISBLANK(comp), BLANK(), DIVIDE([Input Primary Measure] - comp, comp) )
		formatString: 0.0%;-0.0%;0.0%

	column Column
		isHidden
		formatString: 0
		summarizeBy: sum
		isNameInferred
		sourceColumn: [Column]

		annotation SummarizationSetBy = Automatic

	partition 'MOD Finance Compare Metrics' = calculated
		mode: import
		source = Row("Column", BLANK())
