table 'MOD Finance Compare Inputs'

	measure 'Input Primary Measure' = [MOD_BIND_PRIMARY_MEASURE]

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Input Reference Measure 1' = [MOD_BIND_REFERENCE_MEASURE_1]

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Input Reference Measure 2' = [MOD_BIND_REFERENCE_MEASURE_2]

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Column
		isHidden
		formatString: 0
		summarizeBy: sum
		isNameInferred
		sourceColumn: [Column]

		annotation SummarizationSetBy = Automatic

	partition 'MOD Finance Compare Inputs' = calculated
		mode: import
		source = Row("Column", BLANK())
