table B_PortfolioMolecule
	isHidden
	lineageTag: 18b99e5b-775b-4fb3-8d4c-dc5a48c8b020

	column 'Portfolio Key'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 731709a6-918d-443a-a2d9-02634acac945
		summarizeBy: none
		sourceColumn: portfolio_key

		annotation SummarizationSetBy = Automatic

	column 'Molecule Key'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: a204a9b8-5f98-415d-8f0b-de8e15ee8c64
		summarizeBy: none
		sourceColumn: molecule_key

		annotation SummarizationSetBy = Automatic

	column 'Molecule Position'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: eb792b28-b3cb-4fbe-bb1e-cad6f4c8ffb1
		summarizeBy: none
		sourceColumn: molecule_position

		annotation SummarizationSetBy = Automatic

	partition B_PortfolioMolecule = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(root_path & "bridge_portfolio_molecule.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(
				        #"Promoted Headers",
				        {
				            {"portfolio_key", Int64.Type},
				            {"molecule_key", Int64.Type},
				            {"molecule_position", Int64.Type}
				        }
				    ),
				    #"Buffered Rows" = Table.Buffer(#"Changed Type")
				in
				    #"Buffered Rows"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

