table Channel
	lineageTag: ab769c6d-b444-4e36-bb0c-6af8bd6cad9a

	column 'Channel Key'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: da6589b4-4265-4df2-82d5-87c04aa60cc8
		summarizeBy: none
		sourceColumn: channel_key

		annotation SummarizationSetBy = Automatic

	column Channel
		dataType: string
		lineageTag: 03f2e1c7-4b7e-40d5-b0f0-5887eba9be25
		summarizeBy: none
		sourceColumn: cam_channel_name

		annotation SummarizationSetBy = Automatic

	column 'Contact Type'
		dataType: string
		lineageTag: e1964faf-e929-4ee6-8c31-021bcf262c96
		summarizeBy: none
		sourceColumn: contact_type_name

		annotation SummarizationSetBy = Automatic

	partition Channel = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(root_path & "dim_channel.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(
				        #"Promoted Headers",
				        {
				            {"channel_key", Int64.Type},
				            {"cam_channel_name", type text},
				            {"contact_type_name", type text}
				        },
				        "it-IT"
				    ),
				    #"Buffered Rows" = Table.Buffer(#"Changed Type")
				in
				    #"Buffered Rows"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

