table Country
	lineageTag: 120a5d49-b584-43f1-941b-df71ec008d5e

	column 'Country Key'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 8b8d55f4-18c2-4f95-8de1-3a23c3b8f4b6
		summarizeBy: none
		sourceColumn: country_key

		annotation SummarizationSetBy = Automatic

	column 'Country Code'
		dataType: string
		lineageTag: 1507adac-712b-4819-b41b-075aebcf8fc8
		summarizeBy: none
		sourceColumn: country_code

		annotation SummarizationSetBy = Automatic

	column Country
		dataType: string
		lineageTag: a2c285d4-1387-42a0-bb57-2c8b9b631f96
		summarizeBy: none
		sourceColumn: country_name

		annotation SummarizationSetBy = Automatic

	partition Country = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(root_path & "dim_country.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(
				        #"Promoted Headers",
				        {
				            {"country_key", Int64.Type},
				            {"country_code", type text},
				            {"country_name", type text}
				        }
				    ),
				    #"Buffered Rows" = Table.Buffer(#"Changed Type")
				in
				    #"Buffered Rows"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

