table F_Promo
	isHidden
	lineageTag: 5dea4807-c380-4dcd-8c97-cbf433455d79

	column 'Fact Key'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 9f63d46a-cea6-44e0-a30f-6c881b0a26ad
		summarizeBy: none
		sourceColumn: fact_key

		annotation SummarizationSetBy = Automatic

	column 'Country Key'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 12df8bd7-fd21-49b1-84bb-5468766e58bd
		summarizeBy: none
		sourceColumn: country_key

		annotation SummarizationSetBy = Automatic

	column 'Quarter Key'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 4f4a8f9f-3ecd-48d7-a97f-d0de0a5786bc
		summarizeBy: none
		sourceColumn: quarter_key

		annotation SummarizationSetBy = Automatic

	column 'Product Key'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: c130491a-74c2-4848-948e-aec6244a1c19
		summarizeBy: none
		sourceColumn: product_key

		annotation SummarizationSetBy = Automatic

	column 'Specialty Key'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 1faaf010-d1ae-45fe-9899-873ac8e6ba17
		summarizeBy: none
		sourceColumn: specialty_key

		annotation SummarizationSetBy = Automatic

	column 'Channel Key'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 63a917d5-bd68-402d-91e2-e7940db4b92f
		summarizeBy: none
		sourceColumn: channel_key

		annotation SummarizationSetBy = Automatic

	column 'Feedback Key'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 4ea31821-6f8b-4432-b79c-319737deff27
		summarizeBy: none
		sourceColumn: feedback_key

		annotation SummarizationSetBy = Automatic

	column 'Product Details'
		dataType: int64
		isHidden
		formatString: #,0;-#,0;0
		lineageTag: 5cc0db19-41e5-4a5a-9ee2-f9476e506229
		summarizeBy: sum
		sourceColumn: product_details

		annotation SummarizationSetBy = Automatic

	column 'Contact Number'
		dataType: int64
		isHidden
		formatString: #,0;-#,0;0
		lineageTag: bba84e89-3ff0-42c6-a696-0e10f783f7dc
		summarizeBy: sum
		sourceColumn: contact_number

		annotation SummarizationSetBy = Automatic

	column Mentions
		dataType: int64
		isHidden
		formatString: #,0;-#,0;0
		lineageTag: fa88fdcb-52eb-4215-9eed-2369ebfebcfd
		summarizeBy: sum
		sourceColumn: mentions

		annotation SummarizationSetBy = Automatic

	column 'Weighted Calls'
		dataType: double
		isHidden
		formatString: #,0.0;-#,0.0;0.0
		lineageTag: d74a5081-1dda-4005-81fb-7f9ff4f878b6
		summarizeBy: sum
		sourceColumn: weighted_calls

		annotation SummarizationSetBy = Automatic

	column 'Spending Total EUR'
		dataType: double
		isHidden
		formatString: #,0.0;-#,0.0;0.0
		lineageTag: 87f2bf78-ab4a-4331-a96b-6458ad662e06
		summarizeBy: sum
		sourceColumn: spending_total_eur

		annotation SummarizationSetBy = Automatic

	column 'Quality Index'
		dataType: double
		isHidden
		formatString: #,0.0;-#,0.0;0.0
		lineageTag: e7045a22-265a-432d-9aec-76a129eebfe9
		summarizeBy: sum
		sourceColumn: quality_index

		annotation SummarizationSetBy = Automatic

	column 'Converted Contacts'
		dataType: double
		isHidden
		formatString: #,0.0;-#,0.0;0.0
		lineageTag: 51d14da4-c771-434c-ae80-5caefb298114
		summarizeBy: sum
		sourceColumn: converted_contacts

		annotation SummarizationSetBy = Automatic

	partition F_Promo = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(root_path & "fact_promo.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(
				        #"Promoted Headers",
				        {
				            {"fact_key", Int64.Type},
				            {"country_key", Int64.Type},
				            {"quarter_key", Int64.Type},
				            {"product_key", Int64.Type},
				            {"specialty_key", Int64.Type},
				            {"channel_key", Int64.Type},
				            {"feedback_key", Int64.Type},
				            {"product_details", Int64.Type},
				            {"contact_number", Int64.Type},
				            {"mentions", Int64.Type},
				            {"weighted_calls", type number},
				            {"spending_total_eur", type number},
				            {"quality_index", type number},
				            {"converted_contacts", type number}
				        },
				        "it-IT"
				    ),
				    #"Buffered Rows" = Table.Buffer(#"Changed Type")
				in
				    #"Buffered Rows"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

