table F_Sales
	isHidden
	lineageTag: f73b58b7-1156-4c84-bd3c-af9a03d712f8

	column 'Fact Key'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 4f9aef97-6a38-4a79-8a0c-a07de259e865
		summarizeBy: none
		sourceColumn: fact_key

		annotation SummarizationSetBy = Automatic

	column 'Country Key'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 14bdc295-7ceb-424a-94a3-540fbb556387
		summarizeBy: none
		sourceColumn: country_key

		annotation SummarizationSetBy = Automatic

	column 'Sector Key'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 3a5bc135-cb0b-45db-95f7-86a536444fdd
		summarizeBy: none
		sourceColumn: sector_key

		annotation SummarizationSetBy = Automatic

	column 'Quarter Key'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 25985939-ecba-4437-bef5-e5fd71ee6679
		summarizeBy: none
		sourceColumn: quarter_key

		annotation SummarizationSetBy = Automatic

	column 'Diagnosis Key'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 96f9c8e4-c5c3-455b-92ec-fc6a40d5963c
		summarizeBy: none
		sourceColumn: diagnosis_key

		annotation SummarizationSetBy = Automatic

	column 'Product Key'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: edebe0ab-2d02-46f8-b3e9-ae480a07e0c1
		summarizeBy: none
		sourceColumn: product_key

		annotation SummarizationSetBy = Automatic

	column Units
		dataType: int64
		isHidden
		formatString: #,0;-#,0;0
		lineageTag: 73ffe2cd-a996-4f2b-a019-1fb4ec79ef5f
		summarizeBy: sum
		sourceColumn: units

		annotation SummarizationSetBy = Automatic

	column 'Counting Units'
		dataType: int64
		isHidden
		formatString: #,0;-#,0;0
		lineageTag: 14dafe51-c0bc-4b2a-8c16-7f4b16ef6d76
		summarizeBy: sum
		sourceColumn: counting_units

		annotation SummarizationSetBy = Automatic

	column Values
		dataType: double
		isHidden
		formatString: #,0.0;-#,0.0;0.0
		lineageTag: 66d97987-8e7b-48c2-bb93-600f6cbb34be
		summarizeBy: sum
		sourceColumn: eur_mnf

		annotation SummarizationSetBy = Automatic

	partition F_Sales = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(root_path & "fact_sales.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(
				        #"Promoted Headers",
				        {
				            {"fact_key", Int64.Type},
				            {"country_key", Int64.Type},
				            {"sector_key", Int64.Type},
				            {"quarter_key", Int64.Type},
				            {"diagnosis_key", Int64.Type},
				            {"product_key", Int64.Type},
				            {"units", Int64.Type},
				            {"counting_units", Int64.Type},
				            {"eur_mnf", type number}
				        }
				    ),
				    #"Buffered Rows" = Table.Buffer(#"Changed Type")
				in
				    #"Buffered Rows"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

