table Portfolio
	lineageTag: e734b2c8-e9db-48e3-984b-c774c2404aa6

	column 'Portfolio Key'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: e878d0ba-5fec-4cf6-9472-3bce09e7b9b7
		summarizeBy: none
		sourceColumn: portfolio_key

		annotation SummarizationSetBy = Automatic

	column Portfolio
		dataType: string
		lineageTag: 0960df64-f316-4686-8fd4-22f3fe74591d
		summarizeBy: none
		sourceColumn: portfolio_name

		annotation SummarizationSetBy = Automatic

	column 'Molecule Count'
		dataType: int64
		formatString: 0
		lineageTag: 7f1598c3-539f-4850-89e0-51647dbaa765
		summarizeBy: none
		sourceColumn: molecule_count

		annotation SummarizationSetBy = Automatic

	column ATC4
		dataType: string
		lineageTag: 99ef7470-451c-428b-a894-2f3f6fb6a34c
		summarizeBy: none
		sourceColumn: atc4_raw

		annotation SummarizationSetBy = Automatic

	column 'ATC4 Code'
		dataType: string
		lineageTag: 5418a14f-9900-4d36-b3cb-570fe2260e25
		summarizeBy: none
		sourceColumn: atc4_code

		annotation SummarizationSetBy = Automatic

	column 'ATC4 Description'
		dataType: string
		lineageTag: 89d880af-234d-4a64-924b-246981ff4ec3
		summarizeBy: none
		sourceColumn: atc4_description

		annotation SummarizationSetBy = Automatic

	column 'Corporation Group'
		dataType: string
		lineageTag: 19d68695-b208-4f78-bc17-b1d87322b1a0
		summarizeBy: none
		sourceColumn: corporation_group

		annotation SummarizationSetBy = Automatic

	column 'Molecule List'
		dataType: string
		lineageTag: bf36114d-a4e6-4025-b71a-da547c295255
		summarizeBy: none
		sourceColumn: molecule_list

		annotation SummarizationSetBy = Automatic

	column 'Combo Molecule'
		dataType: boolean
		lineageTag: dba54afe-4c89-4215-8b1e-0da7d9d3576b
		summarizeBy: none
		sourceColumn: is_combo_molecule

		annotation SummarizationSetBy = Automatic

	column 'Has Sales'
		dataType: boolean
		isHidden
		lineageTag: 5df1e2fb-2523-4efd-a297-c5aac9c85bab
		summarizeBy: none
		sourceColumn: has_sales

		annotation SummarizationSetBy = Automatic

	column 'Has Promo'
		dataType: boolean
		isHidden
		lineageTag: 327643af-3e0f-416c-a8c9-4b0de1623785
		summarizeBy: none
		sourceColumn: has_promo

		annotation SummarizationSetBy = Automatic

	column 'Has Finance'
		dataType: boolean
		isHidden
		lineageTag: 03e3f9e4-12c8-4f16-8f9d-e7dcabb172c9
		summarizeBy: none
		sourceColumn: has_finance

		annotation SummarizationSetBy = Automatic

	column 'Common 3 Worlds'
		dataType: boolean
		isHidden
		lineageTag: cd27054c-3a46-4ecd-a037-33ad1b75982f
		summarizeBy: none
		sourceColumn: is_common_three_worlds

		annotation SummarizationSetBy = Automatic

	partition Portfolio = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(root_path & "dim_portfolio.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(
				        #"Promoted Headers",
				        {
				            {"portfolio_key", Int64.Type},
				            {"portfolio_name", type text},
				            {"atc4_raw", type text},
				            {"atc4_code", type text},
				            {"atc4_description", type text},
				            {"corporation_group", type text},
				            {"molecule_list", type text},
				            {"molecule_count", Int64.Type},
				            {"is_combo_molecule", type logical},
				            {"has_sales", type logical},
				            {"has_promo", type logical},
				            {"has_finance", type logical},
				            {"is_common_three_worlds", type logical}
				        }
				    ),
				    #"Buffered Rows" = Table.Buffer(#"Changed Type")
				in
				    #"Buffered Rows"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

