table Sector
	lineageTag: 70929cad-c5fd-4447-bf71-19c04464e628

	column 'Sector Key'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: ad7a02c1-419a-4f6d-b27a-ff40c4985dee
		summarizeBy: none
		sourceColumn: sector_key

		annotation SummarizationSetBy = Automatic

	column Sector
		dataType: string
		lineageTag: d514bc6b-be89-4346-944f-c2bcd87fcbe4
		summarizeBy: none
		sourceColumn: sector_name

		annotation SummarizationSetBy = Automatic

	partition Sector = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(root_path & "dim_sector.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(
				        #"Promoted Headers",
				        {
				            {"sector_key", Int64.Type},
				            {"sector_name", type text}
				        }
				    ),
				    #"Buffered Rows" = Table.Buffer(#"Changed Type")
				in
				    #"Buffered Rows"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

