table Country
	lineageTag: 1b1db648-cdd1-42be-9a95-f0391e0a38dc

	column 'Country Key'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: da42698f-05be-4dd5-b162-c04e51b26e51
		summarizeBy: none
		sourceColumn: country_key

		annotation SummarizationSetBy = Automatic

	column 'Country Code'
		dataType: string
		lineageTag: 3dce9a83-3f25-4c08-8892-580f91d5c241
		summarizeBy: none
		sourceColumn: country_code

		annotation SummarizationSetBy = Automatic

	column Country
		dataType: string
		lineageTag: a2bd56a6-6ea7-4b46-9fdf-e394d1506e21
		summarizeBy: none
		sourceColumn: country_name

		annotation SummarizationSetBy = Automatic

	partition Country = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(root_path & "dim_country.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(
				        #"Promoted Headers",
				        {
				            {"country_key", Int64.Type},
				            {"country_code", type text},
				            {"country_name", type text}
				        }
				    ),
				    #"Buffered Rows" = Table.Buffer(#"Changed Type")
				in
				    #"Buffered Rows"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

