table 'MOD Flex Table Metrics'
	lineageTag: 9ad5d329-2db1-4474-a2d1-76b8244d3021

	measure 'Flex Table Selected Value' =
			
			VAR SelectedMeasure = SELECTEDVALUE('MOD Flex Table Measure Selector'[MeasureKey])
			VAR AxisKey = SELECTEDVALUE('MOD Flex Table Axis'[DimensionKey])
			VAR AxisValue = SELECTEDVALUE('MOD Flex Table Axis'[AxisLabel])
			VAR BaseMetric =
			    SWITCH(
			        SelectedMeasure,
			        "metric_1", [Flex Input Metric 1],
			        "metric_2", [Flex Input Metric 2],
			        "metric_3", [Flex Input Metric 3],
			        "metric_4", [Flex Input Metric 4],
			        "metric_5", [Flex Input Metric 5],
			        "metric_6", [Flex Input Metric 6],
			        "metric_7", [Flex Input Metric 7],
			        "metric_8", [Flex Input Metric 8],
			        "metric_9", [Flex Input Metric 9],
			        "metric_10", [Flex Input Metric 10],
			        BLANK()
			    )
			RETURN
			SWITCH(
			    AxisKey,
			    "dimension_1",
			        CALCULATE(
			            BaseMetric,
			            KEEPFILTERS(TREATAS({AxisValue}, MOD_BIND_DIMENSION_1[Value]))
			        ),
			    "dimension_2",
			        CALCULATE(
			            BaseMetric,
			            KEEPFILTERS(TREATAS({AxisValue}, MOD_BIND_DIMENSION_2[Value]))
			        ),
			    "dimension_3",
			        CALCULATE(
			            BaseMetric,
			            KEEPFILTERS(TREATAS({AxisValue}, MOD_BIND_DIMENSION_3[Value]))
			        ),
			    "dimension_4",
			        CALCULATE(
			            BaseMetric,
			            KEEPFILTERS(TREATAS({AxisValue}, MOD_BIND_DIMENSION_4[Value]))
			        ),
			    "dimension_5",
			        CALCULATE(
			            BaseMetric,
			            KEEPFILTERS(TREATAS({AxisValue}, MOD_BIND_DIMENSION_5[Value]))
			        ),
			    "dimension_6",
			        CALCULATE(
			            BaseMetric,
			            KEEPFILTERS(TREATAS({AxisValue}, MOD_BIND_DIMENSION_6[Value]))
			        ),
			    BLANK()
			)
		formatString: #,0.00
		lineageTag: 3ad9ece3-2136-42e7-b713-8e3df6e2471a

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Flex Table Row Has Data' =
			
			VAR NonBlankMeasureCount =
			    SUMX(
			        VALUES('MOD Flex Table Measure Selector'[MeasureKey]),
			        VAR CurrentMeasureKey = 'MOD Flex Table Measure Selector'[MeasureKey]
			        RETURN
			            IF(
			                NOT ISBLANK(
			                    CALCULATE(
			                        [Flex Table Selected Value],
			                        TREATAS({CurrentMeasureKey}, 'MOD Flex Table Measure Selector'[MeasureKey])
			                    )
			                ),
			                1,
			                0
			            )
			    )
			RETURN
			IF(NonBlankMeasureCount > 0, 1)
		formatString: 0
		lineageTag: 82c527ac-c700-4f50-9f8a-fba2ab2bcc95

	measure 'Flex Table Title' =
			
			VAR SelectedDimensions =
			    CONCATENATEX(
			        VALUES('MOD Flex Table Axis'[DimensionLabel]),
			        'MOD Flex Table Axis'[DimensionLabel],
			        ", ",
			        'MOD Flex Table Axis'[DimensionSort],
			        ASC
			    )
			RETURN
			"Flexible Metrics Pivot | " & COALESCE(SelectedDimensions, "{{bindingLabel:MOD_BIND_DIMENSION_1[Value]}}")
		lineageTag: f7b9e2a3-fc89-4533-ae54-ef56c48fc917

	column Column
		isHidden
		formatString: 0
		lineageTag: 2e00cded-66a0-47a9-a699-ecb837fa9e1b
		summarizeBy: sum
		isNameInferred
		sourceColumn: [Column]

		annotation SummarizationSetBy = Automatic

	partition 'MOD Flex Table Metrics' = calculated
		mode: import
		source = Row("Column", BLANK())
