table 'MOD Flex Table Inputs'
	lineageTag: e3d3436e-43d8-4c20-95bd-e4dd73eb61d6

	measure 'Flex Input Metric 1' = [MOD_BIND_MEASURE_1]
		lineageTag: 01d25c9d-d222-4fb7-b27d-c37a426e2b7a

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Flex Input Metric 2' = [MOD_BIND_MEASURE_2]
		lineageTag: 73186d9b-47d8-418f-922c-9092f88dcd1d

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Flex Input Metric 3' = [MOD_BIND_MEASURE_3]
		lineageTag: 8d7ebfef-ca1b-480d-8209-7e3cf75c2caf

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Flex Input Metric 4' = [MOD_BIND_MEASURE_4]
		formatString: 0
		lineageTag: 97f12a66-7402-4f20-8db3-c9d0afd6a488

	measure 'Flex Input Metric 5' = [MOD_BIND_MEASURE_5]
		formatString: 0
		lineageTag: f6dc89d2-f1df-41cc-a962-fd2205ffcb11

	measure 'Flex Input Metric 6' = [MOD_BIND_MEASURE_6]
		formatString: 0
		lineageTag: 13814cc5-b5cb-4820-9a09-86846d165dc2

	measure 'Flex Input Metric 7' = [MOD_BIND_MEASURE_7]
		formatString: #,0
		lineageTag: 39863427-6d2d-4c81-858a-650a9ea1874a

	measure 'Flex Input Metric 8' = [MOD_BIND_MEASURE_8]
		lineageTag: b333446d-83f2-4c47-9d02-1df64436f8ff

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Flex Input Metric 9' = [MOD_BIND_MEASURE_9]
		lineageTag: dd258a95-f81b-4bcc-9839-d0066009d128

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Flex Input Metric 10' = [MOD_BIND_MEASURE_10]
		lineageTag: 9d10934d-cd86-4b25-95d1-86bb5f4e766f

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Column
		isHidden
		formatString: 0
		lineageTag: e30e19bc-db0f-48eb-9738-b7b9c43d6417
		summarizeBy: sum
		isNameInferred
		sourceColumn: [Column]

		annotation SummarizationSetBy = Automatic

	partition 'MOD Flex Table Inputs' = calculated
		mode: import
		source = Row("Column", BLANK())
