table T_FCT_SALES_A10P
	lineageTag: 58aa389b-3496-45fc-bec9-1220e7bab678

	column Country
		dataType: string
		lineageTag: 73f05f3c-2f67-47a5-b7f4-13d4f7cdbd5b
		summarizeBy: none
		sourceColumn: Country

		annotation SummarizationSetBy = Automatic

	column Sector
		dataType: string
		lineageTag: 71831b88-43eb-41c3-82a3-f7e2636b4ebd
		summarizeBy: none
		sourceColumn: Sector

		annotation SummarizationSetBy = Automatic

	column 'Disease Area'
		dataType: string
		lineageTag: c79ea67e-86f2-4e3a-8d87-45172e4959ff
		summarizeBy: none
		sourceColumn: Disease Area

		annotation SummarizationSetBy = Automatic

	column Disease
		dataType: string
		lineageTag: 9e922bb6-645d-45d4-80f7-793f1f57ab1b
		summarizeBy: none
		sourceColumn: Disease

		annotation SummarizationSetBy = Automatic

	column 'DIAG 3'
		dataType: string
		lineageTag: ab2dc374-8636-42d1-94a4-72d2d44a234a
		summarizeBy: none
		sourceColumn: DIAG 3

		annotation SummarizationSetBy = Automatic

	column 'DIAG 4'
		dataType: string
		lineageTag: 25667563-0c5d-43fc-9ffc-c85f7e0adcf1
		summarizeBy: none
		sourceColumn: DIAG 4

		annotation SummarizationSetBy = Automatic

	column ATC4
		dataType: string
		lineageTag: e31e10bb-200f-4d76-88e3-a86a5194ea26
		summarizeBy: none
		sourceColumn: ATC4

		annotation SummarizationSetBy = Automatic

	column Corporation
		dataType: string
		lineageTag: ec252cca-15ec-44a9-be97-e6e757139db7
		summarizeBy: none
		sourceColumn: Corporation

		annotation SummarizationSetBy = Automatic

	column Molecule
		dataType: string
		lineageTag: ce2cbc97-6573-4747-841b-cb9a82df1690
		summarizeBy: none
		sourceColumn: Molecule

		annotation SummarizationSetBy = Automatic

	column MoleculeNorm
		dataType: string
		lineageTag: ba0ee892-386b-40bb-949a-75328dcb63a8
		summarizeBy: none
		sourceColumn: MoleculeNorm

		annotation SummarizationSetBy = Automatic

	column Product
		dataType: string
		lineageTag: 156a916a-c31f-4215-a2af-b4c815d6974f
		summarizeBy: none
		sourceColumn: Product

		annotation SummarizationSetBy = Automatic

	column Pack
		dataType: string
		lineageTag: 4e20fa2f-5440-40c6-93c5-c79d09348d34
		summarizeBy: none
		sourceColumn: Pack

		annotation SummarizationSetBy = Automatic

	column 'International Prescription'
		dataType: string
		lineageTag: 63b59281-61d9-4e93-9105-7b2232069246
		summarizeBy: none
		sourceColumn: International Prescription

		annotation SummarizationSetBy = Automatic

	column 'Calendar Quarter'
		dataType: string
		lineageTag: 7ec46ed4-e9ad-4112-9f62-80ad2ca48155
		summarizeBy: none
		sourceColumn: Calendar Quarter

		annotation SummarizationSetBy = Automatic

	column QuarterStartDay
		dataType: dateTime
		formatString: Long Date
		lineageTag: bdca131b-9c73-4b01-a398-0fe8986aa3a8
		summarizeBy: none
		sourceColumn: QuarterStartDay

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column QuarterEndDay
		dataType: dateTime
		formatString: Long Date
		lineageTag: 5950e82a-639f-4560-815a-3c4dccea3f0d
		summarizeBy: none
		sourceColumn: QuarterEndDay

		variation Variation
			isDefault
			relationship: 7488aaf1-320b-4054-adaf-b3fda65ceab7
			defaultHierarchy: LocalDateTable_153461ba-e91f-450c-9105-c2fe27de2f77.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Units
		dataType: double
		lineageTag: 32c9c4c7-9809-4a0f-bfcd-85a291420c4c
		summarizeBy: sum
		sourceColumn: Units

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Counting Units'
		dataType: double
		lineageTag: ac51bf5a-3beb-4a3e-a1b7-0431b460a01d
		summarizeBy: sum
		sourceColumn: Counting Units

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'EUR MNF'
		dataType: double
		formatString: #,0.###############\ "€";-#,0.###############\ "€";#,0.###############\ "€"
		lineageTag: 0592169e-eb01-4788-9d5f-ec9d21ec137d
		summarizeBy: sum
		sourceColumn: EUR MNF

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"it-IT"}

	partition T_FCT_SALES_A10P = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(root_path & "PBI A10P.csv"),[Delimiter=",", Columns=18, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Country", type text}, {"Sector", type text}, {"Disease Area", type text}, {"Disease", type text}, {"DIAG 3", type text}, {"DIAG 4", type text}, {"ATC4", type text}, {"Corporation", type text}, {"Molecule List", type text}, {"Product", type text}, {"Pack", type text}, {"International Prescription", type text}, {"Calendar Quarter", type text}, {"QuarterDate", type date}, {"QuarterLabel", type date}, {"Units", type text}, {"Counting Units", type text}, {"EUR MNF", type text}}),
				    #"Uppercased Text" = Table.TransformColumns(#"Changed Type",{{"Country", Text.Upper, type text}, {"Sector", Text.Upper, type text}, {"Disease Area", Text.Upper, type text}, {"Disease", Text.Upper, type text}, {"DIAG 3", Text.Upper, type text}, {"DIAG 4", Text.Upper, type text}, {"ATC4", Text.Upper, type text}, {"Corporation", Text.Upper, type text}, {"Molecule List", Text.Upper, type text}, {"Product", Text.Upper, type text}, {"Pack", Text.Upper, type text}, {"International Prescription", Text.Upper, type text}, {"Calendar Quarter", Text.Upper, type text}}),
				    #"Trimmed Text" = Table.TransformColumns(#"Uppercased Text",{{"Country", Text.Trim, type text}, {"Sector", Text.Trim, type text}, {"Disease Area", Text.Trim, type text}, {"Disease", Text.Trim, type text}, {"DIAG 3", Text.Trim, type text}, {"DIAG 4", Text.Trim, type text}, {"ATC4", Text.Trim, type text}, {"Corporation", Text.Trim, type text}, {"Molecule List", Text.Trim, type text}, {"Product", Text.Trim, type text}, {"Pack", Text.Trim, type text}, {"International Prescription", Text.Trim, type text}, {"Calendar Quarter", Text.Trim, type text}}),
				    #"Cleaned Text" = Table.TransformColumns(#"Trimmed Text",{{"Country", Text.Clean, type text}, {"Sector", Text.Clean, type text}, {"Disease Area", Text.Clean, type text}, {"Disease", Text.Clean, type text}, {"DIAG 3", Text.Clean, type text}, {"DIAG 4", Text.Clean, type text}, {"ATC4", Text.Clean, type text}, {"Corporation", Text.Clean, type text}, {"Molecule List", Text.Clean, type text}, {"Product", Text.Clean, type text}, {"Pack", Text.Clean, type text}, {"International Prescription", Text.Clean, type text}, {"Calendar Quarter", Text.Clean, type text}}),
				    #"Renamed Columns" = Table.RenameColumns(#"Cleaned Text",{{"Molecule List", "Molecule"}}),
				    #"Duplicated Column" = Table.DuplicateColumn(#"Renamed Columns", "Molecule", "Molecule - Copy"),
				    #"Replaced Value" = Table.ReplaceValue(#"Duplicated Column","!","|",Replacer.ReplaceText,{"Molecule - Copy"}),
				    #"Renamed Columns1" = Table.RenameColumns(#"Replaced Value",{{"Molecule - Copy", "MoleculeNorm"}}),
				    #"Reordered Columns" = Table.ReorderColumns(#"Renamed Columns1",{"Country", "Sector", "Disease Area", "Disease", "DIAG 3", "DIAG 4", "ATC4", "Corporation", "Molecule", "MoleculeNorm", "Product", "Pack", "International Prescription", "Calendar Quarter", "QuarterDate", "QuarterLabel", "Units", "Counting Units", "EUR MNF"}),
				    #"Calculated Start of Quarter" = Table.TransformColumns(#"Reordered Columns",{{"QuarterDate", Date.StartOfQuarter, type date}}),
				    #"Calculated End of Quarter" = Table.TransformColumns(#"Calculated Start of Quarter",{{"QuarterLabel", Date.EndOfQuarter, type date}}),
				    #"Renamed Columns2" = Table.RenameColumns(#"Calculated End of Quarter",{{"QuarterDate", "QuarterstartDay"}, {"QuarterLabel", "QuarterEndDay"}}),
				    #"Replaced Value1" = Table.ReplaceValue(#"Renamed Columns2","€","",Replacer.ReplaceText,{"EUR MNF"}),
				    #"Replaced Value2" = Table.ReplaceValue(#"Replaced Value1",",","",Replacer.ReplaceText,{"Units", "Counting Units", "EUR MNF"}),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Replaced Value2",{{"Units", type number}, {"Counting Units", type number}, {"EUR MNF", type number}}),
				    #"Renamed Columns3" = Table.RenameColumns(#"Changed Type1",{{"QuarterstartDay", "QuarterStartDay"}}),
				    #"Divided Column" = Table.TransformColumns(#"Renamed Columns3", {{"Units", each _ / 1000, type number},
				{"Counting Units", each _ / 1000, type number},
				{"EUR MNF", each _ / 1000, type number}})
				in
				    #"Divided Column"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

