table T_DIM_PRODUCT
	lineageTag: e1b8bb1d-4089-493d-983f-c5766ab3e753

	column Product
		dataType: string
		lineageTag: 6aa8838b-215e-49c4-9970-039246a0ed18
		summarizeBy: none
		sourceColumn: Product

		annotation SummarizationSetBy = Automatic

	column ATC4
		dataType: string
		lineageTag: b99f8514-e436-4698-9d60-813d325dc396
		summarizeBy: none
		sourceColumn: ATC4

		annotation SummarizationSetBy = Automatic

	column Corporation
		dataType: string
		lineageTag: 85f46637-52ef-4870-a6fc-12f1d43b0642
		summarizeBy: none
		sourceColumn: Corporation

		annotation SummarizationSetBy = Automatic

	column MoleculeNorm
		dataType: string
		lineageTag: 5513c36c-2169-488e-8c9b-72072aa5a379
		summarizeBy: none
		sourceColumn: MoleculeNorm

		annotation SummarizationSetBy = Automatic

	column 'ATC4 Code'
		dataType: string
		lineageTag: d8013a78-cdb5-4f1a-8bcb-75e8455962a6
		summarizeBy: none
		sourceColumn: ATC4 Code

		annotation SummarizationSetBy = Automatic

	partition T_DIM_PRODUCT = m
		mode: import
		source =
				let
				    Source = Table.Combine({T_FCT_SALES_A10P, T_FCT_PROMO_A10P_CD}),
				    #"Removed Other Columns" = Table.SelectColumns(Source,{"ATC4", "Corporation", "MoleculeNorm", "Product"}),
				    #"Removed Duplicates" = Table.Distinct(#"Removed Other Columns"),
				    #"Sorted Rows" = Table.Sort(#"Removed Duplicates",{{"ATC4", Order.Ascending}}),
				    #"Duplicated Column" = Table.DuplicateColumn(#"Sorted Rows", "ATC4", "ATC4 - Copy"),
				    #"Extracted First Characters" = Table.TransformColumns(#"Duplicated Column", {{"ATC4 - Copy", each Text.Start(_, 5), type text}}),
				    #"Renamed Columns" = Table.RenameColumns(#"Extracted First Characters",{{"ATC4 - Copy", "ATC4 Code"}}),
				    #"Reordered Columns" = Table.ReorderColumns(#"Renamed Columns",{"ATC4 Code", "ATC4", "Corporation", "MoleculeNorm", "Product"})
				in
				    #"Reordered Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

