table 'MOD Finance Compare Selector'
	lineageTag: 59c0a145-385a-4804-b92f-7c6ef0272f73

	measure 'Finance Compare (Selected)' =
			
			SWITCH(
			  SELECTEDVALUE('MOD Finance Compare Selector'[Compare], "vs BDG"),
			  "vs BDG", [Input Fin BDG],
			  "vs PY",  [Input Fin ACT PY]
			)
		lineageTag: 352e890d-98f4-4ab4-a723-4b7f05fa8e69

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Finance Compare Label (Selected)' =
			
			SELECTEDVALUE('MOD Finance Compare Selector'[Label], "BGT")
		lineageTag: e1d92d7f-52f1-4dcd-99bf-8e2fead6966c

	column Compare
		lineageTag: 21031c4b-c02e-44ae-9688-ccd7c2742cca
		summarizeBy: none
		isNameInferred
		sourceColumn: [Compare]

		annotation SummarizationSetBy = Automatic

	column Label
		lineageTag: 3106935f-3cc3-4458-bff9-c1be9e338bff
		summarizeBy: none
		isNameInferred
		sourceColumn: [Label]

		annotation SummarizationSetBy = Automatic

	partition 'MOD Finance Compare Selector' = calculated
		mode: import
		source =
				
				DATATABLE(
				    "Compare", STRING,
				    "Label", STRING,
				    {
				        {"vs BDG", "BGT"},
				        {"vs PY", "PY"}
				    }
				)

