table 'MOD Flex Table Inputs'
	lineageTag: e3d3436e-43d8-4c20-95bd-e4dd73eb61d6

	measure 'Flex Input Sales Values' = [Sales Values]
		lineageTag: 01d25c9d-d222-4fb7-b27d-c37a426e2b7a

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Flex Input Sales Units' = [Sales Units]
		lineageTag: 73186d9b-47d8-418f-922c-9092f88dcd1d

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Flex Input Counting Units' = [Counting Units]
		lineageTag: 8d7ebfef-ca1b-480d-8209-7e3cf75c2caf

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Flex Input Promo Spend' = [Promo Spend]
		formatString: 0
		lineageTag: 97f12a66-7402-4f20-8db3-c9d0afd6a488

	measure 'Flex Input Promo Details' = [Promo Details]
		formatString: 0
		lineageTag: f6dc89d2-f1df-41cc-a962-fd2205ffcb11

	measure 'Flex Input Promo Contacts' = [Promo Contacts]
		formatString: 0
		lineageTag: 13814cc5-b5cb-4820-9a09-86846d165dc2

	measure 'Flex Input Promo Weighted Calls' = [Promo Weighted Calls]
		formatString: #,0
		lineageTag: 39863427-6d2d-4c81-858a-650a9ea1874a

	measure 'Flex Input Fin ACT' = [Fin ACT]
		lineageTag: b333446d-83f2-4c47-9d02-1df64436f8ff

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Flex Input Fin BDG' = [Fin BDG]
		lineageTag: dd258a95-f81b-4bcc-9839-d0066009d128

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Flex Input Fin ACT PY' = [Fin ACT PY]
		lineageTag: 9d10934d-cd86-4b25-95d1-86bb5f4e766f

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Column
		isHidden
		formatString: 0
		lineageTag: e30e19bc-db0f-48eb-9738-b7b9c43d6417
		summarizeBy: sum
		isNameInferred
		sourceColumn: [Column]

		annotation SummarizationSetBy = Automatic

	partition 'MOD Flex Table Inputs' = calculated
		mode: import
		source = Row("Column", BLANK())

