table 'MOD Finance Compare Metrics'
	lineageTag: 427fbda2-de41-4402-8521-ed1c81fa840f

	measure 'Selected Reference Value' = [Finance Compare (Selected)]
		lineageTag: e38421e0-390d-4639-8d3c-dabbc353f59f

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Fin ACT vs (Selected) abs' =
			
			VAR comp = [Finance Compare (Selected)]
			RETURN IF( ISBLANK(comp), BLANK(), [Input Fin ACT] - comp )
		lineageTag: 2f77c01f-c36b-4a9b-a0bf-ec3ea89f1e62

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Fin ACT vs (Selected) +/-%' =
			
			VAR comp = [Finance Compare (Selected)]
			RETURN IF( ISBLANK(comp), BLANK(), DIVIDE([Input Fin ACT] - comp, comp) )
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: 55b10ee5-3892-4315-abf2-5e207447861b

	column Column
		isHidden
		formatString: 0
		lineageTag: 3b824806-36b0-43b7-886f-427b33f67757
		summarizeBy: sum
		isNameInferred
		sourceColumn: [Column]

		annotation SummarizationSetBy = Automatic

	partition 'MOD Finance Compare Metrics' = calculated
		mode: import
		source = Row("Column", BLANK())

