table 'MOD Finance Compare Inputs'
	lineageTag: 5d7b918c-a344-4a56-8e17-a521a0f4e148

	measure 'Input Fin ACT' = [Fin ACT]
		lineageTag: 9b8927e3-ffca-4b5f-b606-a3fbbf5aecc4

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Input Fin BDG' = [Fin BDG]
		lineageTag: bf34deb6-9866-426a-910a-8b398798391f

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Input Fin ACT PY' = [Fin ACT PY]
		lineageTag: 4f2af6a8-e779-4dc7-baa4-f43456e7cf52

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Column
		isHidden
		formatString: 0
		lineageTag: 6c719d99-fdec-4843-888d-3ce8aed39c37
		summarizeBy: sum
		isNameInferred
		sourceColumn: [Column]

		annotation SummarizationSetBy = Automatic

	partition 'MOD Finance Compare Inputs' = calculated
		mode: import
		source = Row("Column", BLANK())

