table 'MOD Finance Compare Inputs'
	lineageTag: f53b4c68-ac32-4c70-8568-ec07071e3750

	measure 'Input Fin ACT' = [Fin ACT]
		lineageTag: c5a94178-5f99-47ff-b1b3-09662452870a

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Input Fin BDG' = [Fin BDG]
		lineageTag: 10a8a099-198f-467b-8acc-7cc7fb63f0a1

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Input Fin ACT PY' = [Fin ACT PY]
		lineageTag: e5f5dd77-69a5-4bb0-bddb-dde6bb9677d1

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Column
		isHidden
		formatString: 0
		lineageTag: 839216be-ec94-47a1-919a-7c431c22a881
		summarizeBy: sum
		isNameInferred
		sourceColumn: [Column]

		annotation SummarizationSetBy = Automatic

	partition 'MOD Finance Compare Inputs' = calculated
		mode: import
		source = Row("Column", BLANK())

