table B_ProductMolecule
	isHidden
	lineageTag: 75bc47ef-6712-419a-80db-7d43877f6839

	column 'Product Key'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 0a011040-9e62-4d54-8b19-d99f36e2ae84
		summarizeBy: none
		sourceColumn: product_key

		annotation SummarizationSetBy = Automatic

	column 'Molecule Key'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 41765342-6b87-4676-8b6c-889859b1e094
		summarizeBy: none
		sourceColumn: molecule_key

		annotation SummarizationSetBy = Automatic

	column 'Molecule Position'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: b0532b46-c570-4c3e-8b39-f9a0f4272f2f
		summarizeBy: none
		sourceColumn: molecule_position

		annotation SummarizationSetBy = Automatic

	partition B_ProductMolecule = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(root_path & "bridge_product_molecule.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(
				        #"Promoted Headers",
				        {
				            {"product_key", Int64.Type},
				            {"molecule_key", Int64.Type},
				            {"molecule_position", Int64.Type}
				        }
				    ),
				    #"Buffered Rows" = Table.Buffer(#"Changed Type")
				in
				    #"Buffered Rows"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

