table Molecule
	lineageTag: 4506cfb2-6a78-44d2-9367-a0202fe36536

	column 'Molecule Key'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: b2d898f1-2331-4d4c-ba75-6e2f85b7ed68
		summarizeBy: none
		sourceColumn: molecule_key

		annotation SummarizationSetBy = Automatic

	column Molecule
		dataType: string
		lineageTag: 1688ab88-a9b3-45f8-978c-96c47be14c7e
		summarizeBy: none
		sourceColumn: molecule_name

		annotation SummarizationSetBy = Automatic

	partition Molecule = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(root_path & "dim_molecule.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(
				        #"Promoted Headers",
				        {
				            {"molecule_key", Int64.Type},
				            {"molecule_name", type text}
				        }
				    ),
				    #"Buffered Rows" = Table.Buffer(#"Changed Type")
				in
				    #"Buffered Rows"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

