table Specialty
	lineageTag: 0a9fffa3-bf40-4451-bcf8-939de8408bf6

	column 'Specialty Key'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 59cb1b06-d1aa-4119-b75e-faa0a3fbba0b
		summarizeBy: none
		sourceColumn: specialty_key

		annotation SummarizationSetBy = Automatic

	column Specialty
		dataType: string
		lineageTag: 17186362-d74d-47da-aa54-b19d2bcf5d12
		summarizeBy: none
		sourceColumn: specialty_name

		annotation SummarizationSetBy = Automatic

	partition Specialty = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(root_path & "dim_specialty.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(
				        #"Promoted Headers",
				        {
				            {"specialty_key", Int64.Type},
				            {"specialty_name", type text}
				        },
				        "it-IT"
				    ),
				    #"Buffered Rows" = Table.Buffer(#"Changed Type")
				in
				    #"Buffered Rows"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

