table B_ProductMolecule
	isHidden
	lineageTag: c5856164-fbd5-429e-82ce-8b296da05c0e

	column 'Product Key'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 5aad4620-adf9-4801-a369-6f02497aff6a
		summarizeBy: none
		sourceColumn: product_key

		annotation SummarizationSetBy = Automatic

	column 'Molecule Key'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: dc352edf-cd27-432e-915a-ffeb06c09307
		summarizeBy: none
		sourceColumn: molecule_key

		annotation SummarizationSetBy = Automatic

	column 'Molecule Position'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 4cd5cc88-c4fa-4138-9040-d815fa67897d
		summarizeBy: none
		sourceColumn: molecule_position

		annotation SummarizationSetBy = Automatic

	partition B_ProductMolecule = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(root_path & "bridge_product_molecule.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(
				        #"Promoted Headers",
				        {
				            {"product_key", Int64.Type},
				            {"molecule_key", Int64.Type},
				            {"molecule_position", Int64.Type}
				        }
				    ),
				    #"Buffered Rows" = Table.Buffer(#"Changed Type")
				in
				    #"Buffered Rows"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

