table Country
	lineageTag: 096b007b-3d4c-44a2-81a8-368f3df9d884

	column 'Country Key'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 48e5da9c-e7ac-47a5-8539-6ad4374d0e85
		summarizeBy: none
		sourceColumn: country_key

		annotation SummarizationSetBy = Automatic

	column 'Country Code'
		dataType: string
		lineageTag: a963148c-ff2b-4ca3-9bbc-3348b8afdf12
		summarizeBy: none
		sourceColumn: country_code

		annotation SummarizationSetBy = Automatic

	column Country
		dataType: string
		lineageTag: c89c139a-12e9-47ba-a56b-e92dea7e4784
		summarizeBy: none
		sourceColumn: country_name

		annotation SummarizationSetBy = Automatic

	partition Country = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(root_path & "dim_country.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(
				        #"Promoted Headers",
				        {
				            {"country_key", Int64.Type},
				            {"country_code", type text},
				            {"country_name", type text}
				        }
				    ),
				    #"Buffered Rows" = Table.Buffer(#"Changed Type")
				in
				    #"Buffered Rows"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

