table F_Finance
	isHidden
	lineageTag: 78096804-8eee-4d02-9300-3d564f0ce446

	column 'Fact Key'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: ab6a09cd-270c-44f9-9aeb-228d35b631c4
		summarizeBy: none
		sourceColumn: fact_key

		annotation SummarizationSetBy = Automatic

	column 'Country Key'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 5001625d-29d7-4431-a370-4e79e4bb54e1
		summarizeBy: none
		sourceColumn: country_key

		annotation SummarizationSetBy = Automatic

	column 'Month Key'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 8496f876-aa85-44a1-8813-85250060fced
		summarizeBy: none
		sourceColumn: month_key

		annotation SummarizationSetBy = Automatic

	column 'Product Key'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: d9531144-3201-4542-aace-70ff75c6baec
		summarizeBy: none
		sourceColumn: product_key

		annotation SummarizationSetBy = Automatic

	column 'ACT Mth Value'
		dataType: double
		isHidden
		formatString: #,0.0;-#,0.0;0.0
		lineageTag: 2357649a-45c3-4493-b5b4-8ba83c6ae26b
		summarizeBy: sum
		sourceColumn: act_mth

		annotation SummarizationSetBy = Automatic

	column 'BDG Mth Value'
		dataType: double
		isHidden
		formatString: #,0.0;-#,0.0;0.0
		lineageTag: 694807b8-f085-4b39-9d84-e2f0728522bf
		summarizeBy: sum
		sourceColumn: bdg_mth

		annotation SummarizationSetBy = Automatic

	partition F_Finance = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(root_path & "fact_cana_finance_monthly.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(
				        #"Promoted Headers",
				        {
				            {"fact_key", Int64.Type},
				            {"country_key", Int64.Type},
				            {"month_key", Int64.Type},
				            {"product_key", Int64.Type},
				            {"act_mth", type number},
				            {"bdg_mth", type number}
				        },
				        "en-US"
				    ),
				    #"Buffered Rows" = Table.Buffer(#"Changed Type")
				in
				    #"Buffered Rows"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

