table Molecule
	lineageTag: 8088987a-dbf7-45b3-adae-14ca99e64373

	column 'Molecule Key'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 41eaad04-a111-4907-a968-7fb61e01d6b1
		summarizeBy: none
		sourceColumn: molecule_key

		annotation SummarizationSetBy = Automatic

	column Molecule
		dataType: string
		lineageTag: 850bd849-8813-4962-8844-6873290772d2
		summarizeBy: none
		sourceColumn: molecule_name

		annotation SummarizationSetBy = Automatic

	partition Molecule = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(root_path & "dim_molecule.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(
				        #"Promoted Headers",
				        {
				            {"molecule_key", Int64.Type},
				            {"molecule_name", type text}
				        }
				    ),
				    #"Buffered Rows" = Table.Buffer(#"Changed Type")
				in
				    #"Buffered Rows"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

